import * as crypto from 'crypto';
import * as pako from 'pako';

export const TYPE_DATA = 0x01;
export const TYPE_NACK = 0x02;
export const TYPE_SYNC = 0x03;
export const TYPE_KEY_REQ = 0x04;
export const TYPE_KEY_SHARE = 0x08;
export const TYPE_MEMBER_INFO = 0x09;
export const TYPE_DICT_RESET = 0x06;
export const TYPE_ACK = 0x07;

// Delta compression is bounded to the last DICT_WINDOW messages of a sender,
// so sender and receiver build identical dictionaries deterministically and
// clients can prune older history (bounded memory).
export const DICT_WINDOW = 200;

// 4-byte SHA-256 fingerprint of the dictionary, carried in the Data header's
// extension area. Receivers verify it before inflating so a dictionary
// desync is detected immediately and recovered in a single step.
export const DICT_FP_LEN = 4;

// roomKeys[convId][epoch] = the group key for that epoch. The server NEVER
// holds these — they are generated by a room member and shared member-to-member
// through the server (which only relays opaque ciphertexts).
export const roomKeys: Map<number, Map<number, Buffer>> = new Map();

// The epoch the local client is currently encrypting with, per conversation.
export const currentEpochs: Map<number, number> = new Map();

// Alias for the current key (convenience for existing callers).
export function getCurrentKey(convId: number): Buffer | undefined {
  return roomKeys.get(convId)?.get(currentEpochs.get(convId) || 1);
}

// We now maintain keys per-conversation
export const convKeys: Map<number, Buffer> = new Map();

export interface DataDart {
  type: number;
  convId: number;
  senderId: number;
  seq: number;
  payload: string; 
}

export interface NackDart {
  type: number;
  convId: number;
  senderId: number;
  missingSeq: number[];
}

export interface SyncDart {
  type: number;
  convId: number;
  senderId: number;
  highestSeq: number;
}

export interface KeyReqDart {
  type: number;
  convId: number;
  senderId: number;
  reqNonce: Buffer;
  clientPubKey: Buffer;
}

// A member-to-member group-key share, relayed opaquely by the server. The
// payload (the 32-byte group key) is ECDH-encrypted to the target member.
export interface KeyShareDart {
  type: number;
  convId: number;
  senderId: number;
  targetId: number;
  epoch: number;
  nonce: Buffer;
  encryptedKey: Buffer; // GCM ciphertext+tag of the group key
}

// Server-authenticated membership roster. The server encrypts it to the member
// using the server's long-term key + the member's public key, so a client that
// pins the server's fingerprint can trust it.
export interface MemberInfo {
  type: number;
  convId: number;
  senderId: number;
  serverPubKey: Buffer;
  creator: boolean;
  members: { senderId: number; pubKey: Buffer }[];
}

export interface DictResetDart {
  type: number;
  convId: number;
  senderId: number;
  targetId: number;
}

export interface AckDart {
  type: number;
  convId: number;
  senderId: number;
  targetId: number;
  seq: number;
}

export interface DecryptedData {
  type: number;
  convId: number;
  senderId: number;
  seq: number;
  compressed: Buffer;
  dictFp: Buffer;
}

// First 4 bytes of SHA-256(dict). Both the sender and every receiver compute
// this over their own (windowed) dictionary; a mismatch means lost history.
export function dictFingerprint(dict: Buffer): Buffer {
  return crypto.createHash('sha256').update(dict).digest().subarray(0, DICT_FP_LEN);
}

export class Codec {
  static encodeDataHelper(dart: DataDart, dict: Buffer): Buffer {
    const epoch = currentEpochs.get(dart.convId) || 1;
    const convKey = roomKeys.get(dart.convId)?.get(epoch);
    if (!convKey) {
      throw new Error(`No group key for Conv ${dart.convId} epoch ${epoch}`);
    }

    const payload = Buffer.from(dart.payload, 'utf-8');
    const compressed = Buffer.from(pako.deflateRaw(payload, { dictionary: dict }));

    // 7-byte cleartext header: type(1) | convId(2) | seq(3) | extLen(1).
    // The 18-byte extension carries the 12-byte GCM nonce + 2-byte key epoch +
    // 4-byte dictionary fingerprint. The header stays independent of the
    // sender's identity; senderId travels inside the encrypted payload.
    const nonce = crypto.randomBytes(12);
    const dictFp = dictFingerprint(dict);

    const header = Buffer.alloc(7);
    header.writeUInt8(dart.type, 0);
    header.writeUInt16BE(dart.convId, 1);
    header.writeUIntBE(dart.seq, 3, 3);
    header.writeUInt8(12 + 2 + DICT_FP_LEN, 6); // ext len = nonce + epoch + dict fingerprint

    const epochBuf = Buffer.alloc(2);
    epochBuf.writeUInt16BE(epoch, 0);
    const aad = Buffer.concat([header, nonce, epochBuf, dictFp]);

    const plaintext = Buffer.alloc(2 + compressed.length);
    plaintext.writeUInt16BE(dart.senderId, 0);
    compressed.copy(plaintext, 2);

    const cipher = crypto.createCipheriv('aes-256-gcm', convKey, nonce);
    cipher.setAAD(aad);

    const encryptedPayload = Buffer.concat([cipher.update(plaintext), cipher.final()]);
    const tag = cipher.getAuthTag();

    return Buffer.concat([aad, encryptedPayload, tag]);
  }

  static decryptData(buf: Buffer): DecryptedData {
    const type = buf.readUInt8(0);
    const convId = buf.readUInt16BE(1);
    const seq = buf.readUIntBE(3, 3);
    const extLen = buf.readUInt8(6);

    // Workaround for potential browserify-aes subarray/view bugs by copying the buffers
    const aad = Buffer.from(buf.subarray(0, 7 + extLen));
    const nonce = Buffer.from(aad.subarray(7, 7 + 12));
    const epoch = aad.readUInt16BE(7 + 12);
    const dictFp = Buffer.from(aad.subarray(7 + 12 + 2, 7 + extLen));
    const encryptedPayload = Buffer.from(buf.subarray(7 + extLen, buf.length - 16));
    const tag = Buffer.from(buf.subarray(buf.length - 16));

    const convKey = roomKeys.get(convId)?.get(epoch);
    if (!convKey) {
      throw new Error(`No group key for Conv ${convId} epoch ${epoch}`);
    }

    const decipher = crypto.createDecipheriv('aes-256-gcm', convKey, nonce);
    decipher.setAAD(aad);
    decipher.setAuthTag(tag);

    const plaintext = Buffer.concat([decipher.update(encryptedPayload), decipher.final()]);
    const senderId = plaintext.readUInt16BE(0);
    const compressed = Buffer.from(plaintext.subarray(2));

    return { type, convId, senderId, seq, compressed, dictFp };
  }

  static inflateData(compressed: Buffer, dict: Buffer): string {
    const payloadBuffer = Buffer.from(pako.inflateRaw(compressed, { dictionary: dict }));
    return payloadBuffer.toString('utf-8');
  }

  static encodeNack(nack: NackDart): Buffer {
    const convKey = getCurrentKey(nack.convId);
    if (!convKey) {
      throw new Error(`No conversation key established for Conv ${nack.convId}`);
    }

    // 17-byte cleartext header: type(1) | convId(2) | senderId(2) | nonce(12).
    // A fresh random nonce per packet eliminates the GCM nonce-reuse that the
    // old fixed sentinel IV (0xFFFFFFFE) allowed.
    const nonce = crypto.randomBytes(12);

    const header = Buffer.alloc(17);
    header.writeUInt8(nack.type, 0);
    header.writeUInt16BE(nack.convId, 1);
    header.writeUInt16BE(nack.senderId, 3);
    nonce.copy(header, 5);

    const payload = Buffer.alloc(2 + nack.missingSeq.length * 3);
    payload.writeUInt16BE(nack.missingSeq.length, 0);
    let offset = 2;
    for (const seq of nack.missingSeq) {
      payload.writeUIntBE(seq, offset, 3);
      offset += 3;
    }

    const cipher = crypto.createCipheriv('aes-256-gcm', convKey, nonce);
    cipher.setAAD(header);
    const encryptedPayload = Buffer.concat([cipher.update(payload), cipher.final()]);
    const tag = cipher.getAuthTag();
    
    return Buffer.concat([header, encryptedPayload, tag]);
  }

  static decodeNack(buf: Buffer): NackDart {
    const type = buf.readUInt8(0);
    const convId = buf.readUInt16BE(1);
    const senderId = buf.readUInt16BE(3);
    const header = Buffer.from(buf.subarray(0, 17));
    const nonce = Buffer.from(header.subarray(5));
    const encryptedPayload = Buffer.from(buf.subarray(17, buf.length - 16));
    const tag = Buffer.from(buf.subarray(buf.length - 16));
    
    const convKey = getCurrentKey(convId);
    if (!convKey) {
      throw new Error(`No conversation key established for Conv ${convId}`);
    }
    const decipher = crypto.createDecipheriv('aes-256-gcm', convKey, nonce);
    decipher.setAAD(header);
    decipher.setAuthTag(tag);
    
    const payload = Buffer.concat([decipher.update(encryptedPayload), decipher.final()]);
    
    const missingSeq = [];
    const count = payload.readUInt16BE(0);
    let offset = 2;
    for (let i = 0; i < count; i++) {
      missingSeq.push(payload.readUIntBE(offset, 3));
      offset += 3;
    }
    return { type, convId, senderId, missingSeq };
  }
  
  static encodeSync(sync: SyncDart): Buffer {
    const convKey = getCurrentKey(sync.convId);
    if (!convKey) {
      throw new Error(`No conversation key established for Conv ${sync.convId}`);
    }

    // 17-byte cleartext header: type(1) | convId(2) | senderId(2) | nonce(12).
    const nonce = crypto.randomBytes(12);

    const header = Buffer.alloc(17);
    header.writeUInt8(sync.type, 0);
    header.writeUInt16BE(sync.convId, 1);
    header.writeUInt16BE(sync.senderId, 3);
    nonce.copy(header, 5);

    const payload = Buffer.alloc(3);
    payload.writeUIntBE(sync.highestSeq, 0, 3);

    const cipher = crypto.createCipheriv('aes-256-gcm', convKey, nonce);
    cipher.setAAD(header);
    const encryptedPayload = Buffer.concat([cipher.update(payload), cipher.final()]);
    const tag = cipher.getAuthTag();
    
    return Buffer.concat([header, encryptedPayload, tag]);
  }

  static decodeSync(buf: Buffer): SyncDart {
    const type = buf.readUInt8(0);
    const convId = buf.readUInt16BE(1);
    const senderId = buf.readUInt16BE(3);
    const header = Buffer.from(buf.subarray(0, 17));
    const nonce = Buffer.from(header.subarray(5));
    const encryptedPayload = Buffer.from(buf.subarray(17, buf.length - 16));
    const tag = Buffer.from(buf.subarray(buf.length - 16));
    
    const convKey = getCurrentKey(convId);
    if (!convKey) {
      throw new Error(`No conversation key established for Conv ${convId}`);
    }
    const decipher = crypto.createDecipheriv('aes-256-gcm', convKey, nonce);
    decipher.setAAD(header);
    decipher.setAuthTag(tag);
    
    const payload = Buffer.concat([decipher.update(encryptedPayload), decipher.final()]);
    const highestSeq = payload.readUIntBE(0, 3);
    return { type, convId, senderId, highestSeq };
  }

  static encodeKeyReq(req: KeyReqDart): Buffer {
    const header = Buffer.alloc(5);
    header.writeUInt8(req.type, 0);
    header.writeUInt16BE(req.convId, 1);
    header.writeUInt16BE(req.senderId, 3);
    return Buffer.concat([header, req.reqNonce, req.clientPubKey]);
  }

  static decodeKeyReq(buf: Buffer): KeyReqDart {
    const type = buf.readUInt8(0);
    const convId = buf.readUInt16BE(1);
    const senderId = buf.readUInt16BE(3);
    const reqNonce = Buffer.from(buf.subarray(5, 21));
    const clientPubKey = Buffer.from(buf.subarray(21));
    return { type, convId, senderId, reqNonce, clientPubKey };
  }

  // SHA-256 hex fingerprint of the server's static ECDH public key. Clients pin
  // this value to authenticate the server (SSH-style host-key verification), so
  // an active man-in-the-middle can't substitute its own key.
  static serverFingerprint(serverPubKey: Buffer): string {
    return crypto.createHash('sha256').update(serverPubKey).digest('hex');
  }

  // KEY_SHARE: member -> member group-key delivery, relayed opaquely by the
  // server. transportKey = SHA-256(ECDH(sharer's key, target's pubkey)).
  static encodeKeyShare(share: KeyShareDart, transportKey: Buffer): Buffer {
    const header = Buffer.alloc(21);
    header.writeUInt8(share.type, 0);
    header.writeUInt16BE(share.convId, 1);
    header.writeUInt16BE(share.senderId, 3);
    header.writeUInt16BE(share.targetId, 5);
    header.writeUInt16BE(share.epoch, 7);
    share.nonce.copy(header, 9);

    const cipher = crypto.createCipheriv('aes-256-gcm', transportKey, share.nonce);
    cipher.setAAD(header);
    const encryptedKey = Buffer.concat([cipher.update(share.encryptedKey), cipher.final(), cipher.getAuthTag()]);
    return Buffer.concat([header, encryptedKey]);
  }

  static decodeKeyShare(buf: Buffer, transportKey: Buffer): { epoch: number; groupKey: Buffer } {
    if (buf.length < 21 + 48) {
      throw new Error('buffer too short');
    }
    const epoch = buf.readUInt16BE(7);
    const header = Buffer.from(buf.subarray(0, 21));
    const nonce = Buffer.from(header.subarray(9));
    const encryptedKey = Buffer.from(buf.subarray(21, buf.length - 16));
    const tag = Buffer.from(buf.subarray(buf.length - 16));

    const decipher = crypto.createDecipheriv('aes-256-gcm', transportKey, nonce);
    decipher.setAAD(header);
    decipher.setAuthTag(tag);
    const groupKey = Buffer.concat([decipher.update(encryptedKey), decipher.final()]);
    return { epoch, groupKey };
  }

  // MEMBER_INFO: server -> member roster. transportKey = SHA-256(ECDH(server
  // key, member pubkey)). The AAD binds the header + the server's public key,
  // so a client that pins the server fingerprint trusts the roster.
  static encodeMemberInfo(info: MemberInfo, transportKey: Buffer): Buffer {
    const header = Buffer.alloc(5);
    header.writeUInt8(info.type, 0);
    header.writeUInt16BE(info.convId, 1);
    header.writeUInt16BE(info.senderId, 3);

    const nonce = crypto.randomBytes(12);
    const payload = Buffer.alloc(1 + 2 + info.members.length * 67);
    payload.writeUInt8(info.creator ? 1 : 0, 0);
    payload.writeUInt16BE(info.members.length, 1);
    let offset = 3;
    for (const m of info.members) {
      payload.writeUInt16BE(m.senderId, offset);
      m.pubKey.copy(payload, offset + 2);
      offset += 67;
    }

    const aad = Buffer.concat([header, info.serverPubKey, nonce]);
    const cipher = crypto.createCipheriv('aes-256-gcm', transportKey, nonce);
    cipher.setAAD(aad);
    const encrypted = Buffer.concat([cipher.update(payload), cipher.final(), cipher.getAuthTag()]);

    return Buffer.concat([header, info.serverPubKey, nonce, encrypted]);
  }

  // Returns the server public key embedded in a MEMBER_INFO packet, so a client
  // can verify the pin and derive the transport key BEFORE decrypting.
  static memberInfoServerKey(buf: Buffer): Buffer {
    if (buf.length < 70) {
      throw new Error('buffer too short');
    }
    return Buffer.from(buf.subarray(5, 70));
  }

  static decodeMemberInfo(buf: Buffer, transportKey: Buffer): MemberInfo {
    if (buf.length < 5 + 65 + 12 + 16) {
      throw new Error('buffer too short');
    }
    const type = buf.readUInt8(0);
    const convId = buf.readUInt16BE(1);
    const senderId = buf.readUInt16BE(3);
    const serverPubKey = Buffer.from(buf.subarray(5, 70));
    const nonce = Buffer.from(buf.subarray(70, 82));
    const encrypted = Buffer.from(buf.subarray(82));

    const header = Buffer.from(buf.subarray(0, 5));
    const aad = Buffer.concat([header, serverPubKey, nonce]);
    const decipher = crypto.createDecipheriv('aes-256-gcm', transportKey, nonce);
    decipher.setAAD(aad);
    decipher.setAuthTag(Buffer.from(encrypted.subarray(encrypted.length - 16)));
    const payload = Buffer.concat([decipher.update(encrypted.subarray(0, encrypted.length - 16)), decipher.final()]);

    const creator = payload.readUInt8(0) === 1;
    const count = payload.readUInt16BE(1);
    const members: { senderId: number; pubKey: Buffer }[] = [];
    let offset = 3;
    for (let i = 0; i < count; i++) {
      const mSenderId = payload.readUInt16BE(offset);
      const pubKey = Buffer.from(payload.subarray(offset + 2, offset + 67));
      members.push({ senderId: mSenderId, pubKey });
      offset += 67;
    }
    return { type, convId, senderId, serverPubKey, creator, members };
  }

  static encodeDictReset(reset: DictResetDart): Buffer {
    const convKey = getCurrentKey(reset.convId);
    if (!convKey) {
      throw new Error(`No conversation key established for Conv ${reset.convId}`);
    }

    // 19-byte cleartext header: type(1) | convId(2) | senderId(2) | targetId(2) | nonce(12).
    // The whole header is the AEAD AAD, so an outsider can't forge a reset.
    const nonce = crypto.randomBytes(12);

    const header = Buffer.alloc(19);
    header.writeUInt8(reset.type, 0);
    header.writeUInt16BE(reset.convId, 1);
    header.writeUInt16BE(reset.senderId, 3);
    header.writeUInt16BE(reset.targetId, 5);
    nonce.copy(header, 7);

    const cipher = crypto.createCipheriv('aes-256-gcm', convKey, nonce);
    cipher.setAAD(header);
    cipher.final();
    const tag = cipher.getAuthTag();
    return Buffer.concat([header, tag]);
  }

  static decodeDictReset(buf: Buffer): DictResetDart {
    if (buf.length < 19) {
      throw new Error('buffer too short');
    }
    const type = buf.readUInt8(0);
    const convId = buf.readUInt16BE(1);
    const senderId = buf.readUInt16BE(3);
    const targetId = buf.readUInt16BE(5);
    const header = Buffer.from(buf.subarray(0, 19));
    const nonce = Buffer.from(header.subarray(7));
    const encryptedPayload = Buffer.from(buf.subarray(19, buf.length - 16));
    const tag = Buffer.from(buf.subarray(buf.length - 16));

    const convKey = getCurrentKey(convId);
    if (!convKey) {
      throw new Error(`No conversation key established for Conv ${convId}`);
    }
    const decipher = crypto.createDecipheriv('aes-256-gcm', convKey, nonce);
    decipher.setAAD(header);
    decipher.setAuthTag(tag);
    Buffer.concat([decipher.update(encryptedPayload), decipher.final()]);

    return { type, convId, senderId, targetId };
  }

  static encodeAck(ack: AckDart): Buffer {
    const convKey = getCurrentKey(ack.convId);
    if (!convKey) {
      throw new Error(`No conversation key established for Conv ${ack.convId}`);
    }

    // 22-byte cleartext header: type(1) | convId(2) | senderId(2) | targetId(2)
    // | seq(3) | nonce(12). The whole header is the AEAD AAD, so an outsider
    // can't forge a delivery confirmation.
    const nonce = crypto.randomBytes(12);

    const header = Buffer.alloc(22);
    header.writeUInt8(ack.type, 0);
    header.writeUInt16BE(ack.convId, 1);
    header.writeUInt16BE(ack.senderId, 3);
    header.writeUInt16BE(ack.targetId, 5);
    header.writeUIntBE(ack.seq, 7, 3);
    nonce.copy(header, 10);

    const cipher = crypto.createCipheriv('aes-256-gcm', convKey, nonce);
    cipher.setAAD(header);
    cipher.final();
    const tag = cipher.getAuthTag();
    return Buffer.concat([header, tag]);
  }

  static decodeAck(buf: Buffer): AckDart {
    if (buf.length < 22) {
      throw new Error('buffer too short');
    }
    const type = buf.readUInt8(0);
    const convId = buf.readUInt16BE(1);
    const senderId = buf.readUInt16BE(3);
    const targetId = buf.readUInt16BE(5);
    const seq = buf.readUIntBE(7, 3);
    const header = Buffer.from(buf.subarray(0, 22));
    const nonce = Buffer.from(header.subarray(10));
    const encryptedPayload = Buffer.from(buf.subarray(22, buf.length - 16));
    const tag = Buffer.from(buf.subarray(buf.length - 16));

    const convKey = getCurrentKey(convId);
    if (!convKey) {
      throw new Error(`No conversation key established for Conv ${convId}`);
    }
    const decipher = crypto.createDecipheriv('aes-256-gcm', convKey, nonce);
    decipher.setAAD(header);
    decipher.setAuthTag(tag);
    Buffer.concat([decipher.update(encryptedPayload), decipher.final()]);

    return { type, convId, senderId, targetId, seq };
  }
}
